// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meoctohgspgpftmdddck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lb2N0b2hnc3BncGZ0bWRkZGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTQwNjYsImV4cCI6MjA1OTA5MDA2Nn0.0ZBMPxTwZ086TZ8B6jKKDU6tvRMkz8eEASMoplhaSRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);